version: "3"
services:
  react:
    build:
      context: ./docker/react
    container_name: react_container
    tty: true
    volumes:
      - ./react:/usr/src/app/react:cached
    command: sh -c "cd /usr/src/app/react/react-app && yarn start"
    ports:
      - "3000:3000"
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: golang_container
    volumes:
      - ./go-app/src:/usr/src/app/go/src
    tty: true
    ports: 
      - 8080:8080
